-- MySQL Script generated by MySQL Workbench
-- mié 20 sep 2017 13:44:58 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema knightrider
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema knightrider
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knightrider` DEFAULT CHARACTER SET latin1 ;
USE `knightrider` ;

-- -----------------------------------------------------
-- Table `knightrider`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`customer` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthdate` DATE NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `driving_license_id` VARCHAR(9) NOT NULL,
  `driving_license_date` DATE NOT NULL,
  PRIMARY KEY (`email`),
  INDEX `fk_vehicle_travel_email_idx` (`email` ASC),
  CONSTRAINT `fk_customer_email`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`customer_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`customer_address` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `number` VARCHAR(45) NOT NULL,
  `floor` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `locality` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_address_customer_idx` (`email` ASC),
  CONSTRAINT `fk_customer_address_customer`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`customer_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`customer_card` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `number` VARCHAR(16) NOT NULL,
  `name` VARCHAR(150) NOT NULL,
  `cvs` INT(3) NOT NULL,
  `date_expired` DATE NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`, `email`),
  INDEX `fk_customer_card_email_idx` (`email` ASC),
  CONSTRAINT `fk_customer_card_email`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`rol` (
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `TeslaBD`.`user_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`user_rol` (
  `email` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`, `rol`),
  INDEX `fk_user_rol_1_idx` (`rol` ASC),
  CONSTRAINT `fk_user_rol_email`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rol_rol`
    FOREIGN KEY (`rol`)
    REFERENCES `knightrider`.`rol` (`rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`vehicle` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `vin` VARCHAR(7) NOT NULL,
  `model` VARCHAR(145) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `state` ENUM('online', 'offline') NOT NULL,
  `rent_state` ENUM('unblocked', 'blocked', 'traveling') NOT NULL,
  `battery_level` INT(11) NOT NULL,
  `battery_range` DOUBLE NOT NULL,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `sun_roof` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`vehicle_travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`vehicle_travel` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_vehicle` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `date_start` TIMESTAMP NOT NULL,
  `latitude_start` DOUBLE NOT NULL,
  `longitude_start` DOUBLE NOT NULL,
  `date_end` TIMESTAMP NULL DEFAULT NULL,
  `latitude_end` DOUBLE NOT NULL,
  `longitude_end` DOUBLE NOT NULL,
  `cost` DOUBLE NOT NULL,
  `time` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vehicle_travel_vehicle_idx` (`id_vehicle` ASC),
  INDEX `fk_vehicle_travel_email_idx` (`email` ASC),
  CONSTRAINT `fk_vehicle_travel_email`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_travel_vehicle`
    FOREIGN KEY (`id_vehicle`)
    REFERENCES `knightrider`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `knightrider`.`vehicle_blocked`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`vehicle_blocked` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `id_vehicle` INT(11) NOT NULL,
  INDEX `fk_vehicle_reserved_email` (`email` ASC),
  INDEX `fk_vehicle_reserved_vehicle1_idx` (`id_vehicle` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_vehicle_reserved_email`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vehicle_reserved_id_vehicle`
    FOREIGN KEY (`id_vehicle`)
    REFERENCES `knightrider`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


-- -----------------------------------------------------
-- Table `knightrider`.`vehicle_traveling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knightrider`.`vehicle_traveling` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `id_vehicle` INT NOT NULL,
  `date_start` TIMESTAMP NOT NULL,
  `battery_start` INT NOT NULL,
  `latitude_start` DOUBLE NOT NULL,
  `longitude_start` DOUBLE NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`),
  INDEX `id_vehicle_idx` (`id_vehicle` ASC),
  CONSTRAINT `email`
    FOREIGN KEY (`email`)
    REFERENCES `knightrider`.`customer` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_vehicle`
    FOREIGN KEY (`id_vehicle`)
    REFERENCES `knightrider`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 0;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
